import type { PixelMap, AnimParams, AnimPresetName, LayerState, GridSize } from "./types";
import { generateKeyframes, getAnimationName } from "./animationEngine";
import { getBottomRows } from "./pixelUtils";

interface ExportOptions {
  pixels: PixelMap;
  gridSize: GridSize;
  activePreset: AnimPresetName;
  animParams: AnimParams;
  layers: LayerState;
  flickerColor: string;
}

export function generateCSS(opts: ExportOptions): string {
  const { pixels, gridSize, activePreset, animParams, layers } = opts;
  const dur = `${animParams.speed}ms`;
  const tim = animParams.timing;
  const animName = getAnimationName(activePreset);

  let css = `/* Generated by PIXEL.CSS — CSS Pixel Animation Builder */\n\n`;
  css += `.pixel-loader { position: relative; display: inline-block; }\n\n`;
  css += `.pixel-grid {\n  display: grid;\n  grid-template-columns: repeat(${gridSize}, 10px);\n  grid-template-rows: repeat(${gridSize}, 10px);\n  gap: 0;\n  image-rendering: pixelated;\n  position: relative;\n`;
  if (layers.float) css += `  animation: ${animName} ${dur} infinite ${tim};\n`;
  css += `}\n\n`;

  const bottomKeys = getBottomRows(pixels, gridSize);
  Object.entries(pixels).forEach(([key, color]) => {
    const [r, c] = key.split(",");
    const isBottom = bottomKeys.has(key);
    const flickerAnim =
      isBottom && layers.flicker
        ? ` animation: ${dur} infinite ${tim} ${(+r + +c) % 2 === 0 ? "anim-flicker0" : "anim-flicker1"};`
        : "";
    css += `.cell-${r}-${c} { background: ${color};${flickerAnim} }\n`;
  });

  css += `\n.pixel-shadow {\n  position: absolute;\n  width: 70%;\n  height: 20%;\n  background: rgba(0,0,0,0.35);\n  border-radius: 50%;\n  filter: blur(6px);\n  bottom: -8px;\n  left: 50%;\n  transform: translateX(-50%);\n`;
  if (layers.shadow) css += `  animation: anim-shadow ${dur} infinite ${tim};\n`;
  css += `}\n`;
  css += generateKeyframes(activePreset, animParams);
  return css;
}

export function generateHTML(opts: ExportOptions): string {
  const { pixels, gridSize } = opts;
  let html = `<div class="pixel-loader">\n  <div class="pixel-grid">\n`;
  for (let r = 0; r < gridSize; r++) {
    for (let c = 0; c < gridSize; c++) {
      const color = pixels[`${r},${c}`];
      if (color) {
        html += `    <div class="cell-${r}-${c}"></div>\n`;
      } else {
        html += `    <div></div>\n`;
      }
    }
  }
  html += `  </div>\n  <div class="pixel-shadow"></div>\n</div>\n`;
  return html;
}

export function generateReact(opts: ExportOptions): string {
  const { pixels, gridSize, activePreset, animParams, layers } = opts;
  const dur = `${animParams.speed}ms`;
  const tim = animParams.timing;
  const animName = getAnimationName(activePreset);
  const bottomKeys = getBottomRows(pixels, gridSize);

  const pixelArr: { color: string; flicker: 0 | 1 | null }[] = [];
  for (let r = 0; r < gridSize; r++) {
    for (let c = 0; c < gridSize; c++) {
      const color = pixels[`${r},${c}`] || "";
      const k = `${r},${c}`;
      const flicker =
        color && bottomKeys.has(k) && layers.flicker ? (((r + c) % 2) as 0 | 1) : null;
      pixelArr.push({ color, flicker });
    }
  }

  const keyframes = generateKeyframes(activePreset, animParams).replace(/`/g, "\\`");

  return `import React from "react";

const GRID = ${gridSize};
const PIXELS = ${JSON.stringify(pixelArr)};

const styles = \`
.plx-loader { position: relative; display: inline-block; }
.plx-grid {
  display: grid;
  grid-template-columns: repeat(\${GRID}, 10px);
  grid-template-rows: repeat(\${GRID}, 10px);
  gap: 0; image-rendering: pixelated; position: relative;
  ${layers.float ? `animation: ${animName} ${dur} infinite ${tim};` : ""}
}
.plx-cell { width: 10px; height: 10px; }
.plx-f0 { animation: anim-flicker0 ${dur} infinite ${tim}; }
.plx-f1 { animation: anim-flicker1 ${dur} infinite ${tim}; }
.plx-shadow {
  position: absolute; width: 70%; height: 20%;
  background: rgba(0,0,0,0.35); border-radius: 50%;
  filter: blur(6px); bottom: -8px; left: 50%;
  transform: translateX(-50%);
  ${layers.shadow ? `animation: anim-shadow ${dur} infinite ${tim};` : ""}
}
${keyframes}
\`;

export default function PixelLoader() {
  return (
    <>
      <style>{styles}</style>
      <div className="plx-loader">
        <div className="plx-grid">
          {PIXELS.map((p, i) => (
            <div
              key={i}
              className={\`plx-cell\${p.flicker === 0 ? " plx-f0" : ""}\${p.flicker === 1 ? " plx-f1" : ""}\`}
              style={{ background: p.color || "transparent" }}
            />
          ))}
        </div>
        <div className="plx-shadow" />
      </div>
    </>
  );
}
`;
}
